version: '3.4'

services:
  eshopwebmvc:
    image: ${DOCKER_REGISTRY-}eshopwebmvc
    ports:
     - "5106:5106"
    environment:
        ConnectionStrings__CatalogConnection: "${MS_SQL_CATALOG_CONNECTION_STRING}"
        ConnectionStrings__IdentityConnection: "${MS_SQL_CATALOG_CONNECTION_STRING}"
        ASPNETCORE_ENVIRONMENT: Docker
        ASPNETCORE_URLS: http://+:5106
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    depends_on:
      - "sqlserver"
  eshoppublicapi:
    image: ${DOCKER_REGISTRY-}eshoppublicapi
    ports:
     - "5200:5200"
    environment:
        ConnectionStrings__CatalogConnection: "${MS_SQL_CATALOG_CONNECTION_STRING}"
        ConnectionStrings__IdentityConnection: "${MS_SQL_CATALOG_CONNECTION_STRING}"
        ASPNETCORE_ENVIRONMENT: Docker
        ASPNETCORE_URLS: http://+:5200
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile
    depends_on:
      - "sqlserver"
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=${SA_PASSWORD}
      - ACCEPT_EULA=Y
volumes:
  data:
    driver: azure_file
    driver_opts:
      share_name: ${AZURE_SHARE_NAME}
      storage_account_name: ${AZURE_STORAGE_ACCOUNT_NAME}
