apiVersion: v1
kind: ConfigMap
metadata:
  name: consul-config
  namespace: consul
data:
  config.json: |
    {
      "ui": true,
      "data_dir": "/consul/data",
      "client_addr": "0.0.0.0",
      "datacenter": "omnis",
      "log_level": "DEBUG",
      "server": true,
      "ports": {
        "dns": 53
      }
    }
