apiVersion: v1
kind: ConfigMap
metadata:
  name: ocelot-config
  namespace: ocelot
data:
  ocelot.json: |
    {
      "Routes": [
        {
          "ServiceName": "identityapi",
          "UpstreamPathTemplate": "/api/v1/identity/{everything}",
          "DownstreamPathTemplate": "/api/v1/{everything}"
        },
        {
          "ServiceName": "identityapi",
          "UpstreamPathTemplate": "/.well-known/{everything}",
          "DownstreamPathTemplate": "/.well-known/{everything}",
          "DelegatingHandlers": [
            "GatewayHeadersDelegationHandler"
          ]
        },
        {
          "ServiceName": "identityapi",
          "UpstreamPathTemplate": "/account/{everything}",
          "DownstreamPathTemplate": "/account/{everything}",
          "DelegatingHandlers": [
            "GatewayHeadersDelegationHandler"
          ]
        },
        {
          "ServiceName": "identityapi",
          "UpstreamPathTemplate": "/connect/{everything}",
          "DownstreamPathTemplate": "/connect/{everything}"
        },
        {
          "ServiceName": "catalogapi",
          "DownstreamScheme": "http",
          "UpstreamPathTemplate": "/api/v1/productcatalog/{everything}",
          "DownstreamPathTemplate": "/api/v1/{everything}",
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityServer",
            "AllowedScopes": [ "webappsgateway" ]
          }
        },
        {
          "ServiceName": "retailapi",
          "DownstreamScheme": "http",
          "UpstreamPathTemplate": "/api/v1/retail/{everything}",
          "DownstreamPathTemplate": "/api/v1/{everything}",
          "AuthenticationOptions": {
            "AuthenticationProviderKey": "IdentityServer",
            "AllowedScopes": [ "webappsgateway" ]
          }
        }
      ],
      "GlobalConfiguration": {
        "ServiceDiscoveryProvider": {
          "Host": "consul.consul.svc.cluster.local",
          "Port": 8500,
          "Type": "Consul"
        }
      }
    }
