apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ocelot-ingress
  namespace: ocelot
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"   
spec:
  rules:
  - host: ocelot.omni-rs.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ocelot
            port:
              number: 7200
  tls:
  - hosts:
    - ocelot.omni-rs.com
    secretName: omni-rs-com-tls-sub 
