apiVersion: v1
kind: Service
metadata:
  name: consul
  namespace: consul
spec:
  selector:
    app: consul
  type: NodePort
  ports:
    - name: consul
      port: 8500
      targetPort: 8500
    - name: dns
      port: 53
      targetPort: 53
    